name: Build Signed Game APK and AAB
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Gradle Automatically
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5

      # Ab koi naya key tool command nahi chalega, direct aapki uploaded key use hogi
      - name: Compile Signed APK and AAB Bundle
        run: |
          gradle :app:bundleRelease
          gradle :app:assembleRelease

      - name: Upload Completed Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Cricket-Manager-26-Signed-Builds
          path: |
            **/build/outputs/apk/release/*.apk
            **/build/outputs/bundle/release/*.aab
