name: Generate Fixed Keystore and PEM
on: workflow_dispatch
jobs:
  keygen:
    runs-on: ubuntu-latest
    steps:
      - name: Create Keystore and Export PEM
        run: |
          # 1. Permanent Keystore banana
          keytool -genkeypair -v -keystore release.keystore -alias cricketalias -keyalg RSA -keysize 2048 -validity 10000 -storepass cricket2026 -keypass cricket2026 -dname "CN=Sumit, O=CricketManager, C=IN"
          
          # 2. Google ke liye .pem Certificate export karna
          keytool -exportcert -alias cricketalias -keystore release.keystore -storepass cricket2026 -file upload_certificate.pem -rfc

      - name: Upload Files as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: My-Permanent-App-Keys
          path: |
            release.keystore
            upload_certificate.pem
