name: Generate Permanent Keystore
on: workflow_dispatch
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Create Keystore File
        run: |
          keytool -genkeypair -v -keystore release.keystore -alias cricketalias -keyalg RSA -keysize 2048 -validity 10000 -storepass cricket2026 -keypass cricket2026 -dname "CN=Sumit, O=CricketManager, C=IN"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: My-App-Keystore
          path: release.keystore
